### ISSUE TITLE
Add new project members

### ISSUE THREAD

**Issue by DerDakon** [notqmail/notqmail#127]
I hereby propose to add 2 new project members:

 * @leahneukirchen
 * @josuah

Both have shown a good understanding of the code, valueable feedback and first PRs. What more can we expect?

So, poll for the already existing project members: what do you think?

**Comment by schmonz** [comment]
Thank you for proposing this. I’m happy to see both of you here and contributing.

This is our first time considering adding new project members since the big bang, when I was inviting whoever I felt like inviting. That worked out well enough but I’d like to come out of this with a wiki page — short and guaranteed incomplete, but a start — with our current thinking about when we want/don’t-want to invite contributors to join the project, and maybe also how to get started contributing.

I have a new poop contributor in my household as of this week, so this is all the thinking I’m capable of. FWIW, I’m aware of no reasons not to want these two to join, only reasons to want them to.

**Comment by schmonz** [comment]
Let me suggest that unless someone objects (or expresses any concerns whatsoever) by May 17, we add both contributors to this GitHub project.

This is me requesting objections, concerns, vague ideas about how to responsibly vet new project members, etc. @alanpost @jlmuir @mbhangui @xenotrope

**Comment by jlmuir** [comment]
Congrats @schmonz on the new baby!

No objections or concerns.  If @DerDakon recommends them, I think that adds significant weight to approving.

I don't have much time to contribute, and I certainly don't want to add any difficulty to the process.  However, since you, @schmonz, asked about vague ideas, I'll just say that I don't have experience with the best way to handle adding new members.  But due to your experience with being a pkgsrc and NetBSD developer, I was half thinking you might draw on that experience to suggest something! :-)  I found [New NetBSD developer application procedure](https://www.netbsd.org/foundation/policies/application-procedure.html) which lays out how NetBSD handles a new developer application.  (I think that in order to become a pkgsrc committer, you have to become a NetBSD developer as well, but I could be wrong.)  So, anyway, it's one method that could be a starting point for us if everyone liked it.

Another idea--and again, I don't really have grounds to be speaking given my very limited contribution level to the project, so I defer to the other more active members--would be to evaluate new member candidates like one might evaluate a job candidate.  In this case, I'm thinking of Joel Spolsky's [Guerrilla Guide to Interviewing (version 3.0)](https://www.joelonsoftware.com/2006/10/25/the-guerrilla-guide-to-interviewing-version-30/).  Again, just a vague idea, so feel free to summarily dismiss the idea without any further thought.  But if anyone's still listening, continuing with the idea, we wouldn't need a programming test since any candidate would presumably be recommended by an existing member.  And maybe in some crazy future we might have project members who don't write software but instead write documentation, or who knows what, so in that case a programming test wouldn't be appropriate.  But Spolsky is looking for two things: (1) smart and (2) gets things done.  We could try to evaluate based on those two criteria.

Anyway, there; two vague ideas.

**Comment by schmonz** [comment]
Thank you @jlmuir for offering some ideas to pursue (both of which are familiar enough to me that I probably act fairly accordingly despite not remembering exactly what they say).

It's nearing the end of May 17 in my timezone. In the absence of objections or concerns about either of our proposed new contributors, in the presence of review bottlenecks we need to ease,  by the precedent where I apparently (at least sometimes) get to decide who joins this GitHub project, and on the strength of their contributions thus far, I've added @leahneukirchen and @josuah.

Welcome, both of you! I'll add you to our dev mailing list and make an announcement there, too.

I'd like to avoid extending this precedent any further. Next time a potential new project member comes around, I strongly wish for us to have a slightly better (and better-documented) decision-making process.
